# Generated by Django 4.0 on 2021-12-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatlesBandComplexModelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermidiate',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
